on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-go-program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Buld Fetch and transfer program
        run: echo start building the program...

      - name: Build and run Go program
        run: |
          go build -o myprogram main.go
          ./myprogram

      - name: Done
        run: echo Done!!!
